# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-25 19:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('karaoke', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='disc',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='karaoke.KaraokeDisc'),
            preserve_default=False,
        ),
    ]
