# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 00:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('karaoke', '0002_song_disc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='karaoke.Artist'),
        ),
        migrations.AlterField(
            model_name='song',
            name='disc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='karaoke.KaraokeDisc'),
        ),
    ]
