# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 05:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaoke', '0004_song_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artist',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='karaokedisc',
            options={'ordering': ('name',)},
        ),
        migrations.AddField(
            model_name='song',
            name='track',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
