# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 05:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaoke', '0005_auto_20161229_0531'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='song',
            name='tag',
            field=models.ManyToManyField(blank=True, to='karaoke.Tag'),
        ),
    ]
